openapi: 3.0.3
info:
  title: BCR CH 6
  version: 1.0.0
  contact: {}
servers:
  - url: 127.0.0.1
  - url: "{{base_url}}"
paths:
  /api/cars:
    get:
      tags:
        - Cars
      summary: Retrieve all cars
      description: Retrieve all cars
      operationId: retrieveAllCars
      responses:
        "200":
          description: All cars
          headers:
            Content-Length:
              schema:
                type: string
                example: "2331"
            Date:
              schema:
                type: string
                example: Mon, 20 May 2024 12:18:08 GMT
            ETag:
              schema:
                type: string
                example: W/"91b-kvf4UqFKT8coejDo5o2A3fB4J+k"
            X-Powered-By:
              schema:
                type: string
                example: Express
          content:
            application/json:
              schema:
                type: object
                properties:
                  cars:
                    type: array
                    items:
                      type: object
                      properties:
                        created_at:
                          type: string
                          example: 2024-05-19T16:25:47.796Z
                        finish_rent:
                          type: string
                          example: 2024-06-18T16:25:47.765Z
                        id:
                          type: number
                          example: 1
                        name:
                          type: string
                          example: Honda Civic
                        picture:
                          type: string
                          nullable: true
                          example: null
                        price:
                          type: number
                          example: 22473
                        start_rent:
                          type: string
                          example: 2024-06-17T16:25:47.765Z
                        updated_at:
                          nullable: true
                          example: null
                    example:
                      - created_at: 2024-05-19T16:25:47.796Z
                        finish_rent: 2024-06-18T16:25:47.765Z
                        id: 1
                        name: Honda Civic
                        picture: null
                        price: 22473
                        start_rent: 2024-06-17T16:25:47.765Z
                        updated_at: null
                      - created_at: 2024-05-19T16:25:47.796Z
                        finish_rent: 2024-06-20T16:25:47.765Z
                        id: 2
                        name: BMW 3 Series
                        picture: null
                        price: 82326
                        start_rent: 2024-06-11T16:25:47.765Z
                        updated_at: null
                      - created_at: 2024-05-19T16:25:47.796Z
                        finish_rent: 2024-05-31T16:25:47.765Z
                        id: 3
                        name: Audi A4
                        picture: null
                        price: 57834
                        start_rent: 2024-05-30T16:25:47.765Z
                        updated_at: null
                      - created_at: 2024-05-19T16:25:47.796Z
                        finish_rent: 2024-06-03T16:25:47.765Z
                        id: 4
                        name: Jeep Wrangler
                        picture: null
                        price: 85435
                        start_rent: 2024-05-27T16:25:47.765Z
                        updated_at: null
                      - created_at: 2024-05-19T16:25:47.796Z
                        finish_rent: 2024-06-09T16:25:47.765Z
                        id: 5
                        name: Mercedes-Benz C-Class
                        picture: null
                        price: 23203
                        start_rent: 2024-06-02T16:25:47.765Z
                        updated_at: null
                      - created_at: 2024-05-19T16:25:47.796Z
                        finish_rent: 2024-06-25T16:25:47.765Z
                        id: 6
                        name: Honda Civic
                        picture: null
                        price: 50778
                        start_rent: 2024-06-15T16:25:47.765Z
                        updated_at: null
                      - created_at: 2024-05-19T16:25:47.796Z
                        finish_rent: 2024-06-21T16:25:47.765Z
                        id: 7
                        name: Volkswagen Golf
                        picture: null
                        price: 27661
                        start_rent: 2024-06-13T16:25:47.765Z
                        updated_at: null
                      - created_at: 2024-05-19T16:25:47.796Z
                        finish_rent: 2024-05-30T16:25:47.765Z
                        id: 8
                        name: Audi A4
                        picture: null
                        price: 13033
                        start_rent: 2024-05-29T16:25:47.765Z
                        updated_at: null
                      - created_at: 2024-05-19T16:25:47.796Z
                        finish_rent: 2024-05-24T16:25:47.765Z
                        id: 9
                        name: Mercedes-Benz C-Class
                        picture: null
                        price: 20473
                        start_rent: 2024-05-21T16:25:47.765Z
                        updated_at: null
                      - created_at: 2024-05-19T16:25:47.796Z
                        finish_rent: 2024-05-29T16:25:47.765Z
                        id: 10
                        name: Chevrolet Corvette
                        picture: null
                        price: 25942
                        start_rent: 2024-05-27T16:25:47.765Z
                        updated_at: null
                      - created_at: 2024-05-19T16:38:10.124Z
                        finish_rent: 2024-06-17T16:25:47.765Z
                        id: 11
                        name: Tesla Model X
                        picture: https://res.cloudinary.com/djepwirkq/image/upload/v1716136689/bcr/sumolhkyinskvk8fq3j4.png
                        price: 1000000000
                        start_rent: 2024-06-16T16:25:47.765Z
                        updated_at: null
                  message:
                    type: string
                    example: success
              examples:
                All cars:
                  value:
                    cars:
                      - created_at: 2024-05-19T16:25:47.796Z
                        finish_rent: 2024-06-18T16:25:47.765Z
                        id: 1
                        name: Honda Civic
                        picture: null
                        price: 22473
                        start_rent: 2024-06-17T16:25:47.765Z
                        updated_at: null
                      - created_at: 2024-05-19T16:25:47.796Z
                        finish_rent: 2024-06-20T16:25:47.765Z
                        id: 2
                        name: BMW 3 Series
                        picture: null
                        price: 82326
                        start_rent: 2024-06-11T16:25:47.765Z
                        updated_at: null
                      - created_at: 2024-05-19T16:25:47.796Z
                        finish_rent: 2024-05-31T16:25:47.765Z
                        id: 3
                        name: Audi A4
                        picture: null
                        price: 57834
                        start_rent: 2024-05-30T16:25:47.765Z
                        updated_at: null
                      - created_at: 2024-05-19T16:25:47.796Z
                        finish_rent: 2024-06-03T16:25:47.765Z
                        id: 4
                        name: Jeep Wrangler
                        picture: null
                        price: 85435
                        start_rent: 2024-05-27T16:25:47.765Z
                        updated_at: null
                      - created_at: 2024-05-19T16:25:47.796Z
                        finish_rent: 2024-06-09T16:25:47.765Z
                        id: 5
                        name: Mercedes-Benz C-Class
                        picture: null
                        price: 23203
                        start_rent: 2024-06-02T16:25:47.765Z
                        updated_at: null
                      - created_at: 2024-05-19T16:25:47.796Z
                        finish_rent: 2024-06-25T16:25:47.765Z
                        id: 6
                        name: Honda Civic
                        picture: null
                        price: 50778
                        start_rent: 2024-06-15T16:25:47.765Z
                        updated_at: null
                      - created_at: 2024-05-19T16:25:47.796Z
                        finish_rent: 2024-06-21T16:25:47.765Z
                        id: 7
                        name: Volkswagen Golf
                        picture: null
                        price: 27661
                        start_rent: 2024-06-13T16:25:47.765Z
                        updated_at: null
                      - created_at: 2024-05-19T16:25:47.796Z
                        finish_rent: 2024-05-30T16:25:47.765Z
                        id: 8
                        name: Audi A4
                        picture: null
                        price: 13033
                        start_rent: 2024-05-29T16:25:47.765Z
                        updated_at: null
                      - created_at: 2024-05-19T16:25:47.796Z
                        finish_rent: 2024-05-24T16:25:47.765Z
                        id: 9
                        name: Mercedes-Benz C-Class
                        picture: null
                        price: 20473
                        start_rent: 2024-05-21T16:25:47.765Z
                        updated_at: null
                      - created_at: 2024-05-19T16:25:47.796Z
                        finish_rent: 2024-05-29T16:25:47.765Z
                        id: 10
                        name: Chevrolet Corvette
                        picture: null
                        price: 25942
                        start_rent: 2024-05-27T16:25:47.765Z
                        updated_at: null
                      - created_at: 2024-05-19T16:38:10.124Z
                        finish_rent: 2024-06-17T16:25:47.765Z
                        id: 11
                        name: Tesla Model X
                        picture: https://res.cloudinary.com/djepwirkq/image/upload/v1716136689/bcr/sumolhkyinskvk8fq3j4.png
                        price: 1000000000
                        start_rent: 2024-06-16T16:25:47.765Z
                        updated_at: null
                    message: success
      security:
        - {}
    post:
      tags:
        - Cars
      summary: Add a car
      description: Add a car
      operationId: addACar
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                finish_rent:
                  type: string
                  example: 2024-06-17T16:25:47.765Z
                image:
                  type: string
                  format: binary
                name:
                  type: string
                  example: Tesla Model Z
                price:
                  type: string
                  example: "1000000"
                start_rent:
                  type: string
                  example: 2024-06-16T16:25:47.765Z
      responses:
        "200":
          description: ""
      security:
        - bearerAuth: []
  /api/cars/{id}:
    get:
      tags:
        - Cars
      summary: Retrieve a car by id
      description: Retrieve a car by id
      operationId: retrieveACarById
      responses:
        "200":
          description: Car Id 1
          headers:
            Content-Length:
              schema:
                type: string
                example: "402"
            Date:
              schema:
                type: string
                example: Mon, 03 Jun 2024 11:28:28 GMT
            ETag:
              schema:
                type: string
                example: W/"192-YHwFPreP8G1M4lT+jm+F6qEzZ0I"
            X-Powered-By:
              schema:
                type: string
                example: Express
          content:
            application/json:
              schema:
                type: object
                properties:
                  car:
                    type: object
                    properties:
                      created_at:
                        type: string
                        example: 2024-05-19T16:25:47.796Z
                      created_by:
                        nullable: true
                        example: null
                      deleted_at:
                        nullable: true
                        example: null
                      deleted_by:
                        nullable: true
                        example: null
                      finish_rent:
                        type: string
                        example: 2024-06-18T16:25:47.765Z
                      id:
                        type: number
                        example: 1
                      name:
                        type: string
                        example: Mazda
                      picture:
                        type: string
                        example: https://res.cloudinary.com/djepwirkq/image/upload/v1716209483/bcr/tpeqy2lzko2jvkvmey9b.jpg
                      price:
                        type: number
                        example: 600000
                      start_rent:
                        type: string
                        example: 2024-06-17T16:25:47.765Z
                      updated_at:
                        type: string
                        example: 2024-05-20T12:51:23.576Z
                      updated_by:
                        nullable: true
                        example: null
                  message:
                    type: string
                    example: success
              examples:
                Car Id 1:
                  value:
                    car:
                      created_at: 2024-05-19T16:25:47.796Z
                      created_by: null
                      deleted_at: null
                      deleted_by: null
                      finish_rent: 2024-06-18T16:25:47.765Z
                      id: 1
                      name: Mazda
                      picture: https://res.cloudinary.com/djepwirkq/image/upload/v1716209483/bcr/tpeqy2lzko2jvkvmey9b.jpg
                      price: 600000
                      start_rent: 2024-06-17T16:25:47.765Z
                      updated_at: 2024-05-20T12:51:23.576Z
                      updated_by: null
                    message: success
      security:
        - {}
    put:
      tags:
        - Cars
      summary: Update a car by id
      description: Update a car by id
      operationId: updateACarById
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                finish_rent:
                  type: string
                  example: 2024-06-18T16:25:47.765Z
                image:
                  type: string
                  format: binary
                name:
                  type: string
                  example: Mazda
                price:
                  type: string
                  example: "600000"
                start_rent:
                  type: string
                  example: 2024-06-17T16:25:47.765Z
      responses:
        "200":
          description: ""
      security:
        - bearerAuth: []
    delete:
      tags:
        - Cars
      summary: Delete a car by id
      description: Delete a car by id
      operationId: deleteACarById
      responses:
        "200":
          description: Delete a car by id
          headers:
            Content-Length:
              schema:
                type: string
                example: "42"
            Date:
              schema:
                type: string
                example: Mon, 03 Jun 2024 11:33:06 GMT
            ETag:
              schema:
                type: string
                example: W/"2a-+bnroIKHpAh8ZMSdKdV9IDVDT0o"
            X-Powered-By:
              schema:
                type: string
                example: Express
          content:
            application/json:
              schema:
                type: object
                properties:
                  isDeleted:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Car deleted
              examples:
                Delete a car by id:
                  value:
                    isDeleted: true
                    message: Car deleted
      security:
        - bearerAuth: []
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          example: "1"
  /auth/login:
    post:
      tags:
        - Auth
      summary: Login
      description: Login
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                  example: aaa
                username:
                  type: string
                  example: superadmin
            examples:
              Login:
                value:
                  password: aaa
                  username: superadmin
      responses:
        "200":
          description: Successful Login
          headers:
            Content-Length:
              schema:
                type: string
                example: "295"
            Date:
              schema:
                type: string
                example: Mon, 03 Jun 2024 11:23:09 GMT
            ETag:
              schema:
                type: string
                example: W/"127-+PKa6Medz6880YuKdUTURT26iAw"
            X-Powered-By:
              schema:
                type: string
                example: Express
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: success
                  token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJzdXBlcmFkbWluIiwicm9sZSI6InN1cGVyYWRtaW4iLCJpYXQiOjE3MTc0MTM3ODksImV4cCI6MTcxODAxODU4OSwiYXVkIjoiYmNyLXVzZXIiLCJpc3MiOiJiY3Itd2ViLXNlcnZlciIsInN1YiI6IjEifQ.URxmJ4p_XUTeFD6Sa8KEiryvPCa1MDW2Hj83Eb1L874
              examples:
                Successful Login:
                  value:
                    message: success
                    token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJzdXBlcmFkbWluIiwicm9sZSI6InN1cGVyYWRtaW4iLCJpYXQiOjE3MTc0MTM3ODksImV4cCI6MTcxODAxODU4OSwiYXVkIjoiYmNyLXVzZXIiLCJpc3MiOiJiY3Itd2ViLXNlcnZlciIsInN1YiI6IjEifQ.URxmJ4p_XUTeFD6Sa8KEiryvPCa1MDW2Hj83Eb1L874
        "401":
          description: Failed login
          headers:
            Content-Length:
              schema:
                type: string
                example: "43"
            Date:
              schema:
                type: string
                example: Mon, 03 Jun 2024 11:27:54 GMT
            ETag:
              schema:
                type: string
                example: W/"2b-2Y60DWM6seg0BBS2GSXYHM3gX1o"
            X-Powered-By:
              schema:
                type: string
                example: Express
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Username or Password mismatch
              examples:
                Failed login:
                  value:
                    message: Username or Password mismatch
      security:
        - {}
  /auth/register:
    post:
      tags:
        - Auth
      summary: Register
      description: Register
      operationId: register
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: orang biasa
                password:
                  type: string
                  example: biasa231
                username:
                  type: string
                  example: orangtidakbiasa
            examples:
              Register:
                value:
                  name: orang biasa
                  password: biasa231
                  username: orangtidakbiasa
      responses:
        "201":
          description: Register Regular User
          headers:
            Content-Length:
              schema:
                type: string
                example: "264"
            Date:
              schema:
                type: string
                example: Mon, 03 Jun 2024 11:28:59 GMT
            ETag:
              schema:
                type: string
                example: W/"108-QBmrjvpmL6/EdJ8X6oCXEpthsik"
            X-Powered-By:
              schema:
                type: string
                example: Express
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: success
                  user:
                    type: object
                    properties:
                      created_at:
                        type: string
                        example: 2024-06-03T11:29:00.161Z
                      deleted_at:
                        nullable: true
                        example: null
                      email:
                        nullable: true
                        example: null
                      id:
                        type: number
                        example: 5
                      name:
                        type: string
                        example: orang biasa
                      password:
                        type: string
                        example: $2b$10$t1U9crWniYJbxVvSua.EQOjgaV1Hx704dlRstIoWX3PxL8cW0qBLO
                      role:
                        type: string
                        example: user
                      updated_at:
                        nullable: true
                        example: null
                      username:
                        type: string
                        example: orangtidakbiasa
              examples:
                Register Regular User:
                  value:
                    message: success
                    user:
                      created_at: 2024-06-03T11:29:00.161Z
                      deleted_at: null
                      email: null
                      id: 5
                      name: orang biasa
                      password: $2b$10$t1U9crWniYJbxVvSua.EQOjgaV1Hx704dlRstIoWX3PxL8cW0qBLO
                      role: user
                      updated_at: null
                      username: orangtidakbiasa
      security:
        - {}
  /auth/me:
    post:
      tags:
        - Auth
      summary: Me
      description: Me
      operationId: me
      responses:
        "200":
          description: Me
          headers:
            Content-Length:
              schema:
                type: string
                example: "276"
            Date:
              schema:
                type: string
                example: Mon, 03 Jun 2024 11:32:01 GMT
            ETag:
              schema:
                type: string
                example: W/"114-sGtkYkvrVNAFsSC8c+HZNrizVl0"
            X-Powered-By:
              schema:
                type: string
                example: Express
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: success
                  user:
                    type: object
                    properties:
                      created_at:
                        type: string
                        example: 2024-06-02T17:56:10.606Z
                      deleted_at:
                        nullable: true
                        example: null
                      email:
                        type: string
                        example: suadmin@bcr.id
                      id:
                        type: number
                        example: 1
                      name:
                        type: string
                        example: superadmin
                      password:
                        type: string
                        example: $2b$10$ET7ZZy07UAiSW2FEONrUMO/P8FMDtGJ8e5Lj6BEDPUkcW0ex2YORC
                      role:
                        type: string
                        example: superadmin
                      updated_at:
                        nullable: true
                        example: null
                      username:
                        type: string
                        example: superadmin
              examples:
                Me:
                  value:
                    message: success
                    user:
                      created_at: 2024-06-02T17:56:10.606Z
                      deleted_at: null
                      email: suadmin@bcr.id
                      id: 1
                      name: superadmin
                      password: $2b$10$ET7ZZy07UAiSW2FEONrUMO/P8FMDtGJ8e5Lj6BEDPUkcW0ex2YORC
                      role: superadmin
                      updated_at: null
                      username: superadmin
      security:
        - bearerAuth: []
  /users/:
    get:
      tags:
        - Users
      summary: Get All Users
      description: Get All Users
      operationId: getAllUsers
      responses:
        "200":
          description: Get All Users
          headers:
            Content-Length:
              schema:
                type: string
                example: "1007"
            Date:
              schema:
                type: string
                example: Mon, 03 Jun 2024 11:32:14 GMT
            ETag:
              schema:
                type: string
                example: W/"3ef-Q64ff/flKC4aLuwNhlIVCLDkJvc"
            X-Powered-By:
              schema:
                type: string
                example: Express
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: success
                  users:
                    type: array
                    items:
                      type: object
                      properties:
                        created_at:
                          type: string
                          example: 2024-06-02T17:56:10.606Z
                        deleted_at:
                          nullable: true
                          example: null
                        email:
                          type: string
                          nullable: true
                          example: suadmin@bcr.id
                        id:
                          type: number
                          example: 1
                        name:
                          type: string
                          example: superadmin
                        password:
                          type: string
                          example: $2b$10$ET7ZZy07UAiSW2FEONrUMO/P8FMDtGJ8e5Lj6BEDPUkcW0ex2YORC
                        role:
                          type: string
                          example: superadmin
                        updated_at:
                          type: string
                          nullable: true
                          example: null
                        username:
                          type: string
                          example: superadmin
                    example:
                      - created_at: 2024-06-02T17:56:10.606Z
                        deleted_at: null
                        email: suadmin@bcr.id
                        id: 1
                        name: superadmin
                        password: $2b$10$ET7ZZy07UAiSW2FEONrUMO/P8FMDtGJ8e5Lj6BEDPUkcW0ex2YORC
                        role: superadmin
                        updated_at: null
                        username: superadmin
                      - created_at: 2024-06-03T11:15:03.840Z
                        deleted_at: null
                        email: null
                        id: 2
                        name: admin agak biasa
                        password: $2b$10$kCb/BGp4jw3tXsp0btSMfOCFzal8XQ8oZcU5AueW5bKbLtjZxHtDm
                        role: admin
                        updated_at: 2024-06-03T11:19:46.599Z
                        username: admin@bcr.id
                      - created_at: 2024-06-03T11:20:39.679Z
                        deleted_at: null
                        email: null
                        id: 4
                        name: orang biasa
                        password: $2b$10$Zs9wHPi8nPIOTCHjLPqOH.zGVVaabqI0U7fq2Htc6F6LGBIsmxq8m
                        role: user
                        updated_at: null
                        username: orangbiasa
                      - created_at: 2024-06-03T11:29:00.161Z
                        deleted_at: null
                        email: null
                        id: 5
                        name: orang biasa
                        password: $2b$10$t1U9crWniYJbxVvSua.EQOjgaV1Hx704dlRstIoWX3PxL8cW0qBLO
                        role: user
                        updated_at: null
                        username: orangtidakbiasa
              examples:
                Get All Users:
                  value:
                    message: success
                    users:
                      - created_at: 2024-06-02T17:56:10.606Z
                        deleted_at: null
                        email: suadmin@bcr.id
                        id: 1
                        name: superadmin
                        password: $2b$10$ET7ZZy07UAiSW2FEONrUMO/P8FMDtGJ8e5Lj6BEDPUkcW0ex2YORC
                        role: superadmin
                        updated_at: null
                        username: superadmin
                      - created_at: 2024-06-03T11:15:03.840Z
                        deleted_at: null
                        email: null
                        id: 2
                        name: admin agak biasa
                        password: $2b$10$kCb/BGp4jw3tXsp0btSMfOCFzal8XQ8oZcU5AueW5bKbLtjZxHtDm
                        role: admin
                        updated_at: 2024-06-03T11:19:46.599Z
                        username: admin@bcr.id
                      - created_at: 2024-06-03T11:20:39.679Z
                        deleted_at: null
                        email: null
                        id: 4
                        name: orang biasa
                        password: $2b$10$Zs9wHPi8nPIOTCHjLPqOH.zGVVaabqI0U7fq2Htc6F6LGBIsmxq8m
                        role: user
                        updated_at: null
                        username: orangbiasa
                      - created_at: 2024-06-03T11:29:00.161Z
                        deleted_at: null
                        email: null
                        id: 5
                        name: orang biasa
                        password: $2b$10$t1U9crWniYJbxVvSua.EQOjgaV1Hx704dlRstIoWX3PxL8cW0qBLO
                        role: user
                        updated_at: null
                        username: orangtidakbiasa
      security:
        - bearerAuth: []
    post:
      tags:
        - Users
      summary: Add new user
      description: Add new user
      operationId: addNewUser
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: admin biasa
                password:
                  type: string
                  example: admin9632
                role:
                  type: string
                  example: admin
                username:
                  type: string
                  example: admin@bcr.id
            examples:
              Add new user:
                value:
                  name: admin biasa
                  password: admin9632
                  role: admin
                  username: admin@bcr.id
      responses:
        "200":
          description: ""
      security:
        - bearerAuth: []
  /users/{id}:
    get:
      tags:
        - Users
      summary: Get User by Id
      description: Get User by Id
      operationId: getUserById
      responses:
        "200":
          description: User Id 2
          headers:
            Content-Length:
              schema:
                type: string
                example: "289"
            Date:
              schema:
                type: string
                example: Mon, 03 Jun 2024 11:32:20 GMT
            ETag:
              schema:
                type: string
                example: W/"121-0eguHZYhoxw+67veaaSwZyvJH3c"
            X-Powered-By:
              schema:
                type: string
                example: Express
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: success
                  user:
                    type: object
                    properties:
                      created_at:
                        type: string
                        example: 2024-06-03T11:15:03.840Z
                      deleted_at:
                        nullable: true
                        example: null
                      email:
                        nullable: true
                        example: null
                      id:
                        type: number
                        example: 2
                      name:
                        type: string
                        example: admin agak biasa
                      password:
                        type: string
                        example: $2b$10$kCb/BGp4jw3tXsp0btSMfOCFzal8XQ8oZcU5AueW5bKbLtjZxHtDm
                      role:
                        type: string
                        example: admin
                      updated_at:
                        type: string
                        example: 2024-06-03T11:19:46.599Z
                      username:
                        type: string
                        example: admin@bcr.id
              examples:
                User Id 2:
                  value:
                    message: success
                    user:
                      created_at: 2024-06-03T11:15:03.840Z
                      deleted_at: null
                      email: null
                      id: 2
                      name: admin agak biasa
                      password: $2b$10$kCb/BGp4jw3tXsp0btSMfOCFzal8XQ8oZcU5AueW5bKbLtjZxHtDm
                      role: admin
                      updated_at: 2024-06-03T11:19:46.599Z
                      username: admin@bcr.id
      security:
        - bearerAuth: []
    put:
      tags:
        - Users
      summary: Update User by Id
      description: Update User by Id
      operationId: updateUserById
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: admin agak biasa
            examples:
              Update User by Id:
                value:
                  name: admin agak biasa
      responses:
        "200":
          description: ""
      security:
        - bearerAuth: []
    delete:
      tags:
        - Users
      summary: Delete User by Id
      description: Delete User by Id
      operationId: deleteUserById
      responses:
        "200":
          description: Delete User by Id
          headers:
            Content-Length:
              schema:
                type: string
                example: "43"
            Date:
              schema:
                type: string
                example: Mon, 03 Jun 2024 11:32:45 GMT
            ETag:
              schema:
                type: string
                example: W/"2b-eYU+EJxwocl62DYzb4fnvPS6Y2o"
            X-Powered-By:
              schema:
                type: string
                example: Express
          content:
            application/json:
              schema:
                type: object
                properties:
                  isDeleted:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: User deleted
              examples:
                Delete User by Id:
                  value:
                    isDeleted: true
                    message: User deleted
      security:
        - bearerAuth: []
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          example: "3"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
tags:
  - name: Cars
  - name: Auth
  - name: Users
